export { DesktopIcon } from './DesktopIcon';
export { Trash } from './Trash';
export { AssistantDesktopIcon } from './AssistantDesktopIcon';
export { ThumbnailIcon } from './ThumbnailIcon';
export {
  FolderIcon,
  TextFileIcon,
  ImageFileIcon,
  LinkIcon,
  TrashEmptyIcon,
  TrashFullIcon,
  AssistantIcon,
} from './PixelIcons';
export {
  CUSTOM_ICON_LIBRARY,
  getIconsByCategory,
  renderCustomIcon,
  type CustomIconId,
  // Colored Folders
  RedFolderIcon,
  BlueFolderIcon,
  GreenFolderIcon,
  PurpleFolderIcon,
  OrangeFolderIcon,
  PinkFolderIcon,
  // Emoji-style Icons
  StarIcon,
  HeartIcon,
  MusicNoteIcon,
  CameraIcon,
  BookIcon,
  GameControllerIcon,
  CoffeeIcon,
  PlanetIcon,
  LightningIcon,
  FireIcon,
  SparkleIcon,
  ClockIcon,
  MailIcon,
  KeyIcon,
  LockIcon,
  GiftIcon,
  FlagIcon,
  LeafIcon,
  SunIcon,
  MoonIcon,
  CloudIcon,
  RainbowIcon,
  DiamondIcon,
  LightbulbIcon,
  RocketIcon,
  PaletteIcon,
  PencilIcon,
  TerminalIcon,
  PhotoIcon,
  HeadphonesIcon,
  HomeIcon,
} from './CustomIconLibrary';
